name: tests

on:
  push:
  pull_request:

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
      - run: uv sync --locked --extra test
      - run: uv run python -m pytest
